name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: $HOME/android-sdk
      ANDROID_SDK_ROOT: $HOME/android-sdk
      ANDROIDSDK: $HOME/android-sdk

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y git zip unzip wget curl \
            autoconf libtool pkg-config \
            zlib1g-dev libffi-dev libssl-dev \
            cmake libncurses6 libstdc++6

      - name: Install Buildozer (PINNED)
        run: |
          pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.36
          pip install python-for-android==2024.1.21

      - name: Setup Android SDK (HARD LOCK FIX)
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk

          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools

          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-*.zip

          mv cmdline-tools latest || true

          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

          # FORCE clean install (QUAN TRỌNG)
          rm -rf $ANDROID_HOME/build-tools
          rm -rf $ANDROID_HOME/platforms

          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2"

          # VERIFY không còn 37
          ls $ANDROID_HOME/build-tools
      - name: Verify Build Tools
        run: |
          ls $HOME/android-sdk/build-tools
      - name: Clean cache (IMPORTANT)
        run: |
          rm -rf .buildozer ~/.buildozer ~/.gradle

      - name: Build APK
        run: |
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          buildozer -v android debug

      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk